global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: "jmespath-proxy"

receivers:
  - name: "jmespath-proxy"
    webhook_configs:
      - url: "http://jmespath-proxy:8000"
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname"]
