apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jmespath-proxy.fullname" . }}
  labels:
    {{- include "jmespath-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jmespath-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jmespath-proxy.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jmespath-proxy.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # JMESPATH_EXPRESSION configuration
            - name: JMESPATH_EXPRESSION
              {{- if .Values.jmespathExpression.fromConfigMap.enabled }}
              valueFrom:
                configMapKeyRef:
                  name: {{ if .Values.jmespathExpression.fromConfigMap.useExisting }}{{ .Values.jmespathExpression.fromConfigMap.name }}{{- else }}{{ include "jmespath-proxy.fullname" . }}-config{{- end }}
                  key: {{ .Values.jmespathExpression.fromConfigMap.key | default "jmespath-expression" }}
              {{- else }}
              value: {{ .Values.jmespathExpression.value | quote }}
              {{- end }}

            # FORWARD_URL configuration
            - name: FORWARD_URL
              {{- if .Values.forwardUrl.fromSecret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.forwardUrl.fromSecret.name }} # Assumes useExisting is true if enabled
                  key: {{ .Values.forwardUrl.fromSecret.key | default "forward-url" }}
              {{- else if .Values.forwardUrl.fromConfigMap.enabled }}
              valueFrom:
                configMapKeyRef:
                  name: {{ if .Values.forwardUrl.fromConfigMap.useExisting }}{{ .Values.forwardUrl.fromConfigMap.name }}{{- else }}{{ include "jmespath-proxy.fullname" . }}-config{{- end }}
                  key: {{ .Values.forwardUrl.fromConfigMap.key | default "forward-url" }}
              {{- else }}
              value: {{ .Values.forwardUrl.value | quote }}
              {{- end }}

            # Other environment variables
            {{- if .Values.env.HTTPX_TIMEOUT }}
            - name: HTTPX_TIMEOUT
              value: {{ .Values.env.HTTPX_TIMEOUT | quote }}
            {{- end }}
            {{- if .Values.env.VERIFY_SSL }}
            - name: VERIFY_SSL
              value: {{ .Values.env.VERIFY_SSL | quote }}
            {{- end }}

            # Basic Auth Username
            {{- if .Values.forwardAuth.basicAuth.username }}
            - name: FORWARD_BASIC_AUTH_USERNAME
              value: {{ .Values.forwardAuth.basicAuth.username | quote }}
            {{- end }}

            # Basic Auth Password
            {{- if .Values.forwardAuth.basicAuth.passwordSecret.enabled }}
            - name: FORWARD_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.forwardAuth.basicAuth.passwordSecret.useExisting }}
                  name: {{ .Values.forwardAuth.basicAuth.passwordSecret.name }}
                  {{- else }}
                  name: {{ include "jmespath-proxy.fullname" . }}-auth
                  {{- end }}
                  key: {{ .Values.forwardAuth.basicAuth.passwordSecret.key | default "forward-basic-auth-password" }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
