apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jmespath-proxy.fullname" . }}
  labels:
    {{- include "jmespath-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jmespath-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jmespath-proxy.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jmespath-proxy.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.env.JMESPATH_EXPRESSION }}
            - name: JMESPATH_EXPRESSION
              value: {{ .Values.env.JMESPATH_EXPRESSION | quote }}
            {{- end }}
            {{- if .Values.env.FORWARD_URL }}
            - name: FORWARD_URL
              value: {{ .Values.env.FORWARD_URL | quote }}
            {{- end }}
            {{- if .Values.env.HTTPX_TIMEOUT }}
            - name: HTTPX_TIMEOUT
              value: {{ .Values.env.HTTPX_TIMEOUT | quote }}
            {{- end }}
            {{- if .Values.env.FORWARD_BASIC_AUTH_USERNAME }}
            - name: FORWARD_BASIC_AUTH_USERNAME
              value: {{ .Values.env.FORWARD_BASIC_AUTH_USERNAME | quote }}
            {{- end }}
            {{- if .Values.env.FORWARD_BASIC_AUTH_PASSWORD }}
            - name: FORWARD_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "jmespath-proxy.fullname" . }}-auth
                  key: forward-basic-auth-password
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
