{{- if .Values.env.FORWARD_BASIC_AUTH_PASSWORD }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jmespath-proxy.fullname" . }}-auth
  labels:
    {{- include "jmespath-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  forward-basic-auth-password: {{ .Values.env.FORWARD_BASIC_AUTH_PASSWORD | b64enc }}
{{- end }}
